####################################################################################
###
### https://github.com/minershive/hiveos-linux/blob/master/hive/miners/custom/20-h-manifest.conf
###
####################################################################################

# The name of the miner
CUSTOM_NAME="NosanaFlight"

# The name of the miner log file
CUSTOM_LOG_BASENAME="/var/log/nosana-flight-sheet"
